### ISSUE TITLE
Plugin needs to be updated

### ISSUE THREAD

**Issue by jorepstein** [michaelperino/CostumeRoomChecker#5]
It cannot be installed in RuneLite version 1.10.33.1 Launcher version 2.7.1

**Comment by l3vines** [comment]
I second this. Would love to be able to use this plugin.

**Comment by michaelperino** [comment]
Thanks for messaging me on this, sorry I missed your notification two weeks ago. Should be fixed in most recent version, waiting on Runelite to approve the update!
